services:
  nginx:
    build: 
      context: ./requirements/nginx
    image: mynginx
    env_file: .env
    environment:
      - TZ=${TZ}
    ports:
      [443:443]
    volumes:
      - webdata:/var/www/html
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm
    networks:
      - inception
  
  php-fpm:
    build: 
      context: ./requirements/wordpress
    image: myphpfpm
    env_file: .env
    environment:
      - TZ=${TZ}
    volumes:
      - webdata:/var/www/html
    networks:
      - inception
  
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mymariadb
    env_file: .env
    environment:
      - TZ=${TZ}
    volumes: 
      - dbdata:/var/lib/mysql
    networks:
      - inception
    restart: on-failure

networks:
  inception:
    driver: bridge

volumes:
  webdata: 
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/webdata
  dbdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
