services:
  nginx:
    build: 
      context: ./requirements/nginx
    image: mynginx
    ports:
      [443:443]
    volumes:
      - webdata:/var/www/html
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm
    networks:
      - inception
  
  php-fpm:
    build: 
      context: ./requirements/wordpress
    image: myphpfpm
    volumes:
      - webdata:/var/www/html
    networks:
      - inception
  
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mymariadb
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  webdata:
